version: "3.5"
services: 
    dns:
        image: rtradetech/coredns-ens:latest
        network_mode: "host"
        volumes:
            - ./configs/Corefile:/coredns/Corefile
    stubby:
        image: mvance/stubby:latest
        restart: always
        pnetwork_mode: "host"
        volumes:
            - ./configs/stubby.yml:/opt/stubby/etc/stubby/stubby.yml
    # TODO(bonedaddy): enable this
    # pihole: # TODO
    #    container_name: pihole
    #    image: pihole/pihole:latest
    #    ports:
    #    - "53:53/tcp"
    #    - "53:53/udp"
    #    - "67:67/udp"
    #    - "80:80/tcp"
    #    - "443:443/tcp"
    #    environment:
    #    TZ: 'America/Chicago'
    #    # WEBPASSWORD: 'set a secure password here or it will be random'
    #    # Volumes store your data between container upgrades
    #    volumes:
    #    - './etc-pihole/:/etc/pihole/'
    #    - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    #    dns:
    #    - 127.0.0.1
    #    - 1.1.1.1
    #    # Recommended but not required (DHCP needs NET_ADMIN)
    #    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #    cap_add:
    #    - NET_ADMIN
    #    restart: unless-stopped

