version: "3.5"
services:
    unbound:
        image: klutchell/unbound
        volumes:
            - /ext-hdd/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
        restart: unless-stopped
        networks:
            pihole_net:
                ipv4_address: 10.0.0.2
    pihole:
        image: pihole/pihole
        dns: 127.0.0.1
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80/tcp"
        depends_on: 
            - unbound
        environment:
          TZ: 'America/Vancouver'
          WEBPASSWORD: passsword
          DNSSEC: "true"
          ServerIP: 0.0.0.0
          DNS1: 10.0.0.2#5053
          DNS2: "no"
          IPv6: "yes"
        volumes:
            - /ext-hdd/pihole-etc/:/etc/pihole
            - /ext-hdd/pihole-dnsmasq.d/:/etc/dnsmasq.d/
        restart: unless-stopped
        networks:
            pihole_net:
                ipv4_address: 10.0.0.3
networks:
    pihole_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/29
